# train and val datasets (image directory or *.txt file with image paths)

train: /loft/open_images_dataset_v6/screening/images/train
val: /loft/open_images_dataset_v6/screening/images/val
test: /loft/open_images_dataset_v6/screening/images/test

# number of classes
nc: 2

# class names
names: ['Human face', 'Vehicle registration plate']
