# train and val datasets (image directory or *.txt file with image paths)

train: /workspace/oid2yolo_proj/yolo/images/train
val: /workspace/oid2yolo_proj/yolo/images/val
test: /workspace/oid2yolo_proj/yolo/images/test

# number of classes
nc: 2

# class names
names: ['Human face', 'Vehicle registration plate']
